name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run Render
      run: ./render-template.py README.md.jinja data/projects.toml > README.md
    - name: Commit results
      run: |
        git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
        git push origin || echo "No changes to commit"

          
