name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: chmod +x ./templates/render-template.py
    - name: Run Render
      run: ./templates/render-template.py README.md data/projects.toml > README.md
    - name: Commit results
      run: |
        git config user.email "alucab@alucab.org"
        git config user.name "alucab"
        git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
        git push origin || echo "No changes to commit"

          
